#!/bin/bash

if [ "$#" -lt 2 ]; then
   echo "gdb_inject.sh <shared library path> <pid>"
   echo
   exit
fi

script=$(mktemp)

echo "attach $1" >> $script
echo "call (void *) __libc_dlopen_mode(\"$2\", 1)" >> $script
echo "detach" >> $script

echo "q" >> $script

gdb -q  --command=$script
rm $script
